on:
  push:
    branches:
      - main
  pull_request:

name: Continuous integration

jobs:
  check:
    name: Test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      spirv_tools_version: "20200928"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - if: ${{ runner.os == 'Windows' }}
        # Runs separately to add spir-v tools to Powershell's Path.
        run: echo "$HOME/spirv-tools/install/bin" >> $env:GITHUB_PATH
      - run: rustup component add rust-src rustc-dev llvm-tools-preview
      # See: https://github.com/EmbarkStudios/rust-gpu/issues/84
      - if: ${{ runner.os == 'macOS' }}
        run: cargo test --workspace --exclude example-runner
      - if: ${{ runner.os != 'macOS' }}
        run: cargo test --workspace
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - run: rustup component add rustfmt clippy rust-src rustc-dev llvm-tools-preview
      - run: cargo fmt --all -- --check
      - run: cargo clippy --workspace --exclude example-runner --all-targets -- -D warnings
